sudo: required

services:
  - docker

before_install:
  - docker build -t elalem/struct-validator .

script:
  - docker run elalem/struct-validator go test -race -coverprofile=coverage.txt -covermode=count
  - docker run elalem/struct-validator go test -race -coverprofile=coverage.txt -covermode=count ./required

after_success:
  - bash <(curl -s https://codecov.io/bash)
