sudo: required

services:
  - go

before_install:
  go get -v github.com/mohamed-elalem/struct-validator

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic . ./required

after_success:
  - bash <(curl -s https://codecov.io/bash)
